### ISSUE TITLE
error when compiling the example-thesis

### ISSUE THREAD

**Issue by proyan** [derric/cleanthesis#105]
Hi
First of all, thanks for the thesis template, it is really nice.

I am having trouble compiling the template that you provide. Specifically, I do not manage to generate the bibliography. I get the following compilation error:

```
LaTeX Warning: Empty bibliography on input line 97.


! Package xkeyval Error: `labelprefix' undefined in families `blx@refcontext'.

See the xkeyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.98 \newrefcontext[labelprefix={@}]
                                    
? 
```

Afterwards, the pdf is generated without the bibliography.
Any ideas on what might be happening here?
Thanks a lot.
Rohan

**Comment by derric** [comment]
Thanks.
Please use [StackExchange](http://tex.stackexchange.com/questions/tagged/cleanthesis) for questions or problems regarding the use of cleanthesis. Don't forget to add the tag "cleanthesis" to  your question. GitHub issues are for development purposes, e.g, reporting actual bugs or requesting new features.

**Comment by proyan** [comment]
Hi Derric,
For now, I am able to work with the 0.3.1 version. I thought it was a bug with the 0.4.0 version, so I raised the issue. 
I'll try to put the detailed question on stack-exchange later.
Thanks for your work
Rohan

**Comment by derric** [comment]
If it works with 0.3.1, I guess it is more about one of the dependencies. Please double check and confirm that all your latex packages are up to date. And please provide some infos about your environment: which OS, which latex dist, ... Also, what about the log, anything else in it which looks relevant?
